### ISSUE TITLE
[Student Feature]: Initial Start leads to Exception

### ISSUE THREAD

**Issue by dfuchss** [kit-sdq/programming-lecture-eclipse-artemis#164]
```
Caused by: java.lang.IllegalArgumentException: Invalid scheme: 'null'
	at org.springframework.web.socket.sockjs.client.SockJsClient.doHandshake(SockJsClient.java:254)
	at org.springframework.web.socket.messaging.WebSocketStompClient.connect(WebSocketStompClient.java:270)
	at org.springframework.web.socket.messaging.WebSocketStompClient.connect(WebSocketStompClient.java:250)
	at org.springframework.web.socket.messaging.WebSocketStompClient.connect(WebSocketStompClient.java:230)
	at org.springframework.web.socket.messaging.WebSocketStompClient.connect(WebSocketStompClient.java:214)
	at edu.kit.kastel.sdq.eclipse.grading.client.websocket.ArtemisFeedbackWebsocket.connect(ArtemisFeedbackWebsocket.java:58)
	at edu.kit.kastel.sdq.eclipse.grading.core.StudentArtemisController.connectToWebsocket(StudentArtemisController.java:171)
	at edu.kit.kastel.sdq.eclipse.grading.core.StudentSystemwideController.connectToWebsocket(StudentSystemwideController.java:247)
	at edu.kit.kastel.eclipse.student.view.controllers.StudentViewController.connectToWebsocket(StudentViewController.java:54)
	at edu.kit.kastel.eclipse.student.view.ui.ArtemisStudentView.<init>(ArtemisStudentView.java:53)
```

will be received at the initial start (because properties are not set) . this leads to a crash of the view. That should be fixed :)

**Comment by dfuchss** [comment]
@bjoern-ehrlinspiel is this bug resolved in your branch :) ?

**Comment by bjoern-ehrlinspiel** [comment]
yes
