### ISSUE TITLE
`Feature`: Allow grading of files that are not in the default "src" directory.

### ISSUE THREAD

**Issue by CDaut** [kit-sdq/programming-lecture-eclipse-artemis#260]
### Describe the bug

Eclipse throws an error when trying to add a custom penalty

### Describe how to reproduce

1. Load a submission
2. Add a custom penalty with -1 points and a description
3. Click okay 
(Multiline custom penaltys enabled)

### Expected behavior

Custom penalty is saved in the Assessment Annotations

### Screenshots

java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at edu.kit.kastel.eclipse.common.view.utilities.AssessmentUtilities.createAssessmentAnnotation(AssessmentUtilities.java:183)
	at edu.kit.kastel.eclipse.grading.view.assessment.CustomButtonDialog.okPressed(CustomButtonDialog.java:178)
	at org.eclipse.jface.dialogs.Dialog.buttonPressed(Dialog.java:468)
	at org.eclipse.jface.dialogs.Dialog.lambda$0(Dialog.java:619)
	at org.eclipse.swt.events.SelectionListener$1.widgetSelected(SelectionListener.java:84)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5895)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1515)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5126)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4581)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:823)
	at org.eclipse.jface.window.Window.open(Window.java:799)
	at edu.kit.kastel.eclipse.grading.view.assessment.ArtemisGradingView.lambda$10(ArtemisGradingView.java:193)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5895)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1515)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5126)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4581)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1154)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1045)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

### Environment

eclipse.buildId=unknown
java.version=19.0.1
java.vendor=N/A
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -perspective edu.kit.kastel.eclipse.grading.view.perspective.Perspective
Command-line arguments:  -os linux -ws gtk -arch x86_64 -perspective edu.kit.kastel.eclipse.grading.view.perspective.Perspective

**Comment by dfuchss** [comment]
@Clemens-Dautermann It's not reproducible on my environment.

Did you selected a line or multiple lines in the source code? Where did you've opened the source code . 

Tests on my system:
![image](https://user-images.githubusercontent.com/22198798/202699487-9db804ff-c8ff-43c6-90d2-f5fd5886dca3.png)

**Comment by Clemens-Dautermann** [comment]
https://user-images.githubusercontent.com/26997544/202703181-603c42f4-9de5-4c17-9416-37984acaba97.mp4

**Comment by Clemens-Dautermann** [comment]
Works for a different submission

**Comment by dfuchss** [comment]
Ah .. you are not grading a "source code" file. Since the student has created the code in "scr" not in "src", the files are not recognized as valid source code.

**Comment by dfuchss** [comment]
I've changed the title. Because that leads to a useful feature.
