### ISSUE TITLE
`Bug`: Grading tool crashes suddenly due to NullPointerException

### ISSUE THREAD

**Issue by Shirkanesi** [kit-sdq/programming-lecture-eclipse-artemis#303]
### Describe the bug

While grading the grading tool just closes. Last relevant line in log is

```
!ENTRY edu.kit.kastel.sdq.eclipse.grading.view 4 0 2023-04-07 10:01:25.497
!MESSAGE Autograder failed: Cannot invoke "org.eclipse.ui.IWorkbenchWindow.getShell()" because "window" is null
!STACK 0
java.lang.NullPointerException: Cannot invoke "org.eclipse.ui.IWorkbenchWindow.getShell()" because "window" is null
    at edu.kit.kastel.eclipse.common.view.utilities.AssessmentUtilities.getWindowsShell(AssessmentUtilities.java:164)
    at edu.kit.kastel.eclipse.common.view.controllers.SWTViewHandler.warn(SWTViewHandler.java:35)
    at edu.kit.kastel.eclipse.common.api.controller.AbstractController.warn(AbstractController.java:38)
    at edu.kit.kastel.eclipse.common.core.GradingSystemwideController.nullCheckMembersAndNotify(GradingSystemwideController.java:257)
    at edu.kit.kastel.eclipse.common.core.GradingSystemwideController.getCurrentProjectName(GradingSystemwideController.java:110)
    at edu.kit.kastel.eclipse.grading.view.assessment.AutograderUtil.lambda$0(AutograderUtil.java:103)
    at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:187)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)

```

This happens sadly quite frequently; grading a single submission in the time between two crashes is nearly impossible.

### Describe how to reproduce

I have no idea what causes this...

### Expected behavior

Artemis should not crash

### Environment

- Debian 11
- ArtemisGrading 4.1.0
- Relase Drop

**Comment by dfuchss** [comment]
I think we can easily check for null in the resp. method.

**Comment by dfuchss** [comment]
We are moving to intelligrade in the near future :)
