### ISSUE TITLE
`Bug`: Grading tool crashes suddenly due to NullPointerException (pt. 2)

### ISSUE THREAD

**Issue by Shirkanesi** [kit-sdq/programming-lecture-eclipse-artemis#316]
### Describe the bug

```
!ENTRY edu.kit.kastel.sdq.eclipse.common.client 1 0 2023-05-11 22:07:57.912
!MESSAGE Got a new Token: eyJxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

!ENTRY edu.kit.kastel.sdq.eclipse.common.client 1 0 2023-05-11 22:07:57.952
!MESSAGE Got Token: true

!ENTRY edu.kit.kastel.sdq.eclipse.common.client 1 0 2023-05-11 22:07:58.013
!MESSAGE Using artemis.praktomat.cs.kit.edu as hostname of artemis. Protocol is https://

!ENTRY edu.kit.kastel.sdq.eclipse.common.client 1 0 2023-05-11 22:07:58.014
!MESSAGE Using artemis.praktomat.cs.kit.edu as hostname of artemis. Protocol is https://

!ENTRY edu.kit.kastel.sdq.eclipse.common.client 1 0 2023-05-11 22:07:58.912
!MESSAGE Logout occured

!ENTRY org.eclipse.ui 4 0 2023-05-11 22:07:58.912
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.NullPointerException: Cannot assign field "returnValue" because "retObj" is null
    at org.eclipse.swt.browser.WebKit$Webkit2AsyncToSync.getCookie_callback(WebKit.java:1237)
    at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4514)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
    at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:568)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1440)

```

### Describe how to reproduce

I have no idea. Happend twice in 5 minutes.

I noticed "logout occured" in the logs. I did not try to log out!

### Expected behavior

No crash

### Environment

- Debian 11

**Comment by tikelespike** [comment]
Hi, I am experiencing the same problem. I'm using Ubuntu 20.04 and Grading Tool v4.7.1 (latest as of today). I noticed the crashes happen mostly when switching back to eclipse from another window.

**Comment by dfuchss** [comment]
In that case, you should use password / username login and not the browser workflow. That should fix the issue. Simply set a password [here](https://artemis.praktomat.cs.kit.edu/account/reset/request)

**Comment by dfuchss** [comment]
We will move to intelligrade in the future. Thus this project will be archived then :)
